import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/globals.css";
import { Navbar, Providers, ShoppingCard, Footer } from "@/components/index";
import { Toaster } from "@/components/ui/toaster";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fendie - Eccommerce Shop",
  description: "Generated by create next app",
};

export default function RootLayoutTwo({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} bg-[#cbd8d9] text-white dark:bg-transparent`}
      >
        <Providers>
          <Navbar />
          {children}
          <ShoppingCard />
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
